### ISSUE TITLE
How to run this sample solution?

### ISSUE THREAD

**Issue by saravanakumarrc** [asc-lab/better-code-with-ddd#2]
I have executed the infra-up.sh and see the docker images are running as expected.
![image](https://user-images.githubusercontent.com/3397763/131301460-051d222f-e650-4ad1-8150-dc41cdded336.png)

but if I run the TacticalDdd project then I see an authorization error.
![image](https://user-images.githubusercontent.com/3397763/131302066-e35a13df-6777-481f-bd55-0d89be4d7a0b.png)
Is there a document I can follow?

**Comment by wojteksuwala** [comment]
Could you please provide more information about the error (exception plus stacktrace) and info on how do you start the application (from VS or using dotnet run)? 
The application requires postgres, rabbitmq (we have that in docker-compose) but also running DebtorRegistryMock (https://github.com/asc-lab/better-code-with-ddd/tree/ef_core/LoanApplication.TacticalDdd/DebtorRegistryMock). Try to run DebtorRegistryMock manually and then start the DDD project.
